name: Create Pull Request
on:
  workflow_dispatch:

jobs:
  create-pr:
    uses: dmitry-shibanov/versions-package-tools/.github/workflows/create-pr-to-update-manifest.yml@add-support-for-arm64
    with:
      tool-name: "node"
    secrets: inherit
